### ISSUE TITLE
Update / refresh BOSC logo

### ISSUE THREAD

**Issue by yochannah** [OBF/homepage-planning#1]
The [BOSC logo](https://github.com/OBF/bosc_materials/blob/master/logos/100px-Pear.png) is a little outdated and we'd like to refresh it. 

Current logo: 
![image](https://cdn.rawgit.com/OBF/bosc_materials/3723f923/logos/100px-Pear.png) 

## Interested in helping out? 
Any Outreachy applicant is welcome to give this a go, if you have some ideas! Maybe you'd like to create a graphic that reflects aspects of the biological/computational/open nature of the OBF, and/or one that integrates nicely with the [recently redesigned OBF logo](https://github.com/OBF/obf-docs/tree/master/logos/new_logo). I suspect we want to keep the pear theme if possible. 

Pop a comment on this issue to say you'd like to contribute, and share any sketches / mocks / attempts you've made, or run ideas by us first in this issue if you like. 

This issue is suitable for more than one contributor to work on. 

### Specs

Once we've agreed on a basic design, we'll need the following: 

- Must be a **vector** graphic. Design in any graphics package you want, but ensure to provide exports in the following formats:
  - SVG
  - PNG
- Bonus points:
  - With "Bioinformatics Open Source Conference" text
  - without "Bioinformatics Open Source Conference" text
  - multiple sizes
  - multiple shapes - e.g. long thin landscape rectangle, square for icons, etc.

When you're ready, post your ideas in this thread for discussion and refinement. 

You'll be credited in the repo for your contribution as well as reaping eternal fame and glory. 

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), or if needed email yochannah@gmail.com

**Comment by simran-pandey** [comment]
Hi!
I would like to contribute to this issue :)

**Comment by yochannah** [comment]
Hey Simran, awesome! Feel free to message me or ask on the issue if you
have any questions

**Comment by simran-pandey** [comment]
![bosc logo](https://user-images.githubusercontent.com/31364051/46777547-6cf4b900-cd2d-11e8-88e0-e4c0a14e9e35.png)

Hi @yochannah 
This is something that I have created. I have kept the Pear theme as before and have added elements to depict the name **Open Bioinformatics Foundation**
Would be needing your feedback and suggestions on the same :) At the same time I'll try to come up with more options.
I have sketched out the logo in Photoshop which is why it's a bit pixelated. I can recreate a vector version  once we finalize on one :)

I had a confusion - Will the logo say **Open Bioinformatics Foundation** or **Bioinformatics Open Source Foundation**?

**Comment by nlharris** [comment]
Hi Simran, thanks for this nice logo! What you have is correct--it should say Bioinformatics Open Source Conference. (I think it would be too confusing to *also* have it say OBF or Open Bioinformatics Foundation, though maybe there's some way to make that work.)

I would prefer if the colors were closer to the original BOSC pear (yellow and darkish green) and/or the softer green of the new OBF logo, rather than the pleasant but not very pear-like teal you have chosen.

**Comment by simran-pandey** [comment]
Hi @nlharris, Thanks for your feedback! I'll work upon it and share the updated version soon :)

**Comment by barretoana** [comment]
Hi! I was wondering, why is the logo a pear? I did some googleling and found out that Bosc is a kind of pear (I'm from Brazil, never heard of it before!) and it made me curious if there's another reason.

**Comment by hlapp** [comment]
That’s exactly the reason! 👍

**Comment by barretoana** [comment]
Is it ok if I give the logo redesign a try too?

**Comment by nlharris** [comment]
Yes, please do!

**Comment by simran-pandey** [comment]
![bosc logo 2](https://user-images.githubusercontent.com/31364051/46846971-aac21200-cdff-11e8-8e5e-4dbbcd1cbcf0.png)
Hi! I tried using the yellow and dark green of the old logo but the yellow text was impossible to read. I googled up and used a pear like green color. However I do feel that the logo is lacking an element which would depict OBF logo like *Open Source* nature. Would need your opinion on the same :)

**Comment by kushinauwu** [comment]
Hi! I'd like to try my hand at this :)

**Comment by yochannah** [comment]
@kushinauwu go ahead! :)

**Comment by yochannah** [comment]
@simran-pandey you've made a nice start! I'm curious what your draft might look like with flush-right text - https://www.printwand.com/blog/basic-alignment-principles-in-graphic-design-with-examples (or possibly justified text?)

**Comment by simran-pandey** [comment]
@yochannah Thanks for linking the article above. I wasn't aware about the flush-right/left alignment. Will try and experiment with different text alignments and share :)

**Comment by barretoana** [comment]
![img_9908](https://user-images.githubusercontent.com/24767117/46891338-ee3c7080-ce3f-11e8-9ddc-15ea6812fb92.JPG)
Hey there! I played around with some ideas, and did some drafts of what I'm thinking for the icon silhouette. What do you think? Those 4 highlighted are my top picks for now. Gonna digitalize them and work on some alternatives.

**Comment by yochannah** [comment]
@thepurpleana Nice drafts! My personal favourite is the pear with the helix, but all four of the highlighted ones are nifty.

**Comment by simran-pandey** [comment]
![bosf logo 11](https://user-images.githubusercontent.com/31364051/46903050-2a79da80-ceed-11e8-9241-5a62ccf82b9c.jpg)

Hi! I was just wondering what if we make the **B** of Bioinformatics itself look like a pear?

**Comment by yochannah** [comment]
I'm loving seeing you all get inspired from one another! That's a nice draft, @simran-pandey

**Comment by kushinauwu** [comment]
![bosc_0](https://user-images.githubusercontent.com/14867092/46904792-73d72380-cf07-11e8-87a9-a8620e68a7d3.jpeg)
![bosc_1](https://user-images.githubusercontent.com/14867092/46904797-80f41280-cf07-11e8-90ed-56fa2a5d2b4d.jpeg)
Here's an idea I have with a color alternative. Kind of a transparent pear wrapped by a single helix as a reference to open source and biology?

**Comment by yochannah** [comment]
Wow, @kushinauwu - that's very pretty! I'd like to see how it might be paired with text if possible. Also, what would this one look like when printing in black & white?

**Comment by kushinauwu** [comment]
@yochannah  I'll try adding the text as well! 
![bosc_1_bnw](https://user-images.githubusercontent.com/14867092/46904942-f52fb580-cf09-11e8-83b4-e716ba7c309b.jpeg)
Somewhat like this. Did you mean a strict black and white print?

**Comment by yochannah** [comment]
@kushinauwu I think possibly having a strict black & white option might be necessary. While the translucent greys are pretty, I'm thinking that if this was printed out on a black&white printer in a small size (e.g. 1cm*1cm, perhaps at part of the heading for a document) then it might not be clear it's a pear+helix. Does that make sense? Here's some interesting /relevant reading:

- http://atelierlks.com/logo-design-mistakes-and-how-to-avoid-them/
- https://curioelectro.com/black-and-white-logo-design

**Comment by kushinauwu** [comment]
I removed the blending and made the highlight solid
![slide1dfghiyt](https://user-images.githubusercontent.com/14867092/46906654-8f045c00-cf24-11e8-85d4-a74e45f32eba.png)

Here's a minimal version
![presentation2](https://user-images.githubusercontent.com/14867092/46906655-8f045c00-cf24-11e8-85a8-48980fdb4467.png)

**Comment by kushinauwu** [comment]
Here's some versions I did with text earlier 😅
![presentation1_edited](https://user-images.githubusercontent.com/14867092/46906815-0c30d080-cf27-11e8-8639-b0106f6432db.jpg)

**Comment by barretoana** [comment]
Hey guys! :) how you doing? It's raining a lot here today so I'm enjoying my day by working on the project! HAHAHA :P 

So, I created a folder in my fork with all the files I have until now, you can check it out here: 
https://github.com/thepurpleana/homepage/tree/master/design-ideas/BOSC-logo-ideas
Feel free to download them and edit anyway you feel like! 

<img width="681" alt="base-elements-ss" src="https://user-images.githubusercontent.com/24767117/46908017-5a77ac80-cef2-11e8-9578-609cd047d9ff.png">

Just so we have a better idea of where I'm planning on going, with my favorites I came up with some designs:
<img width="348" alt="screen shot 2018-10-13 at 13 41 00" src="https://user-images.githubusercontent.com/24767117/46908026-87c45a80-cef2-11e8-82fa-09316140639f.png">

What do you think? I selected some fonts that match the icon design, but nothing is final! 

Oh! Is the readme ok? I wanted to try my hand at a (pseudo)documentation, never done that before so I just did what felt right.

**Comment by kushinauwu** [comment]
@thepurpleana love your designs! They look so professional!

**Comment by sakshi97** [comment]
Hi! Great designs being discussed :) I would like to give the logo redesign a try as well.

**Comment by sakshi97** [comment]
![whatsapp image 2018-10-14 at 11 26 36 pm](https://user-images.githubusercontent.com/19373793/46920225-a87ed400-d008-11e8-85f2-86b966270b9a.jpeg)


 Hi @yochannah. Came up with a few drafts. The ones marked pink are my top picks. 
I was thinking the pear-shaped open lock might integrate well with the new OBF logo, but it doesn't look that good right now. Let me know what you think! 
The pride leaves might add a nice touch!

**Comment by yochannah** [comment]
So many great designs! ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ 

The helix around the pear by @sakshi97 is nice - it looks like it would mesh with the OBF logo nicely. 
@thepurpleana's half-open pear silhouette looks pretty nifty too! 
@kushinauwu - liking the monochrome options!

**Comment by yochannah** [comment]
BTW, y'all: I've set up a gitter chat: https://gitter.im/OBF/homepage - come by and say hi!!

**Comment by yochannah** [comment]
@thepurpleana I just noticed you asked fo some feedback on your readme - I assume you mean this one? https://github.com/thepurpleana/homepage/tree/master/design-ideas/BOSC-logo-ideas it has some nice detail, good job! I especially like that you added font details.

**Comment by nlharris** [comment]
It's so cool to see all these great new takes on the BOSC logo! One of my logo thoughts, though I’m not sure how it would actually look, is that the keyhole in the OBF logo looks like an upside-down pear. What if it were instead a rightside-up pear, and that pear could then become the BOSC logo (either by itself, or as part of the OBF logo, symbolizing the fact that OBF is the parent organization of BOSC)? (Note that some of @sakshi97's designs incorporate the keyhole motif in the pear, though not in the way I'm describing.)
By the way, I would consider it not out of the question to change the OBF logo itself in this way (turn the keyhole the other way up) if it made sense.

**Comment by kushinauwu** [comment]
@nlharris oh yes! Had thought about the keyhole pear and tried sketching it out, but it looked a little too small. I think we might be able to come up with a way to redesign it the way you suggested if the keyhole could be a little bigger too? Let's try it!

**Comment by sakshi97** [comment]
![whatsapp image 2018-10-15 at 10 08 24 am](https://user-images.githubusercontent.com/19373793/46930328-9c276500-d062-11e8-9ba2-dc1b6130ac28.jpeg)

Hi @nlharris. Tried out a few rough sketches. The current keyhole in OBF logo doesn't really look good turned upside-down. I think a 'man-shaped' keyhole resembles a pear better. Let me know what you think!

**Comment by nlharris** [comment]
@sakshi97 I agree the keyhole would need to be larger for it to work, though I'm not sure why you had to change the shape of the pear. Seems like something more like the sketch on the top right above could work?

**Comment by kushinauwu** [comment]
![pear2_edrftgy7h8u_edited](https://user-images.githubusercontent.com/14867092/47100085-5205d580-d254-11e8-884e-07fdeb7cde7e.jpg)
Here's a single color icon idea.

**Comment by ffelder** [comment]
I would like to contribute .

**Comment by ffelder** [comment]
![bioinformatics logo](https://user-images.githubusercontent.com/42352362/47105239-478b1200-d23b-11e8-9ea6-39411f393bc1.png)

**Comment by jyoti-u** [comment]
Hi,
I would like to contribute.

**Comment by barretoana** [comment]
Wow! Some really nice ideas! You guys inspire me. Good job :D

**Comment by jyoti-u** [comment]
![bio](https://user-images.githubusercontent.com/42260543/47256003-8806ad80-d43e-11e8-827b-168f4fe08e82.jpg)

**Comment by jyoti-u** [comment]
Kindly have look @yochannah

**Comment by yochannah** [comment]
Wow, _so many_ beautiful contributions! 

@jyox007 - I like the look of the logo you've made. What would it look like if it was small - would it till be readable? (think like if it was on the top right corner of letterheaded paper)

@ffelder - Nice having the O as a pear! I have the same question - how might the logo look if really small? 

If anyone else is waiting for feedback and I've missed you, let me know! :)

**Comment by kushinauwu** [comment]
@yochannah I am, the comment probably got lost in there. :) It's this one - https://github.com/OBF/homepage/issues/1#issuecomment-430689978

**Comment by yochannah** [comment]
@kushinauwu thanks for the reminder 👍 I think the top bit of the helix doesn't quite merge with the left wall of the pear quite right but other than that it's pleasantly simple. I really liked your colourful ones too, though! :) 🍐

**Comment by myllah** [comment]
Hello, my name is Mylena and I would like to contribute. I've been thinking about this for some days and I hope you like my ideas.

**Comment by peterjc** [comment]
I liked the rainbow leaf idea in one of @sakshi97's images - that might even work with the old logo or some of the other contributions as an accent for events or publicity specifically promoting diversity.

**Comment by jyoti-u** [comment]
Hey @yochannah good to see you !
I did some changes kindly have a look.

![pear](https://user-images.githubusercontent.com/42260543/47290310-70f1c800-d5c4-11e8-9c6f-7ce581dd81e9.jpg)

**Comment by myllah** [comment]
![main-text2 svg](https://user-images.githubusercontent.com/16190760/47292589-da320500-d5dd-11e8-9a72-f8f55b77af44.png)
![main svg](https://user-images.githubusercontent.com/16190760/47292590-da320500-d5dd-11e8-8731-34e043f9e1a2.png)
[BOSC logo.tar.gz](https://github.com/OBF/homepage/files/2501318/BOSC.logo.tar.gz)

I spent a few days scribbling over it. Then I mixed the pear and a lamp.

**Comment by simran-pandey** [comment]
![logo - 4](https://user-images.githubusercontent.com/31364051/47383946-731e6880-d723-11e8-9877-e6a486f97494.png)
![logo - logo 2](https://user-images.githubusercontent.com/31364051/47383957-7ca7d080-d723-11e8-928f-fa1fb6759f7c.png)
![obf logo 1](https://user-images.githubusercontent.com/31364051/47383972-83364800-d723-11e8-88d2-dd4c61862e2a.png)
![logo - logo 3](https://user-images.githubusercontent.com/31364051/47383964-803b5780-d723-11e8-86f7-4f8c869d6add.png)

I see some really nice designs being discussed here :) I was just wondering what if we replace the DNA symbol and play around a bit as suggested by @nlharris :D

**Comment by sakshi97** [comment]
Hi @yochannah . Here is a draft of my idea. I went with a half-helix around the pear. Let me know if you feel the whole helix is more in-sync with the OBF logo. 
![screenshot 19](https://user-images.githubusercontent.com/19373793/47547074-9f97d780-d911-11e8-8d44-b81802f59882.png)
![screenshot 20](https://user-images.githubusercontent.com/19373793/47547080-a3c3f500-d911-11e8-9ccf-750faa2e9ca8.png)

**Comment by yochannah** [comment]
So many nice contributions! @sakshi97 - the way the logo outline becomes the helix and merges in perfectly is nice! I think I like the leafy version better. 

@simran-pandey wow, more logo contributions! 

@myllah - The hand-drawn style and light bulb look is really unique! Can I ask what software you used to make it?

If I've missed anyone please let me know! <3 <3 <3

**Comment by yochannah** [comment]
One more thing to add for everyone - _Don't forget to record your contributions on the Outreachy site_!! :) You've all been doing so much creative and thoughtful work!! It doesn't have to be merged to count as awesome contributions. 

Also, anyone who wishes to strengthen their application - I'd recommend focusing on the homepage mockup / plans issue here: https://github.com/OBF/homepage/issues/3- while the two logo issues have given you a chance to showcase your graphic design skills, the mockup issue will give you the chance to showcase your html / css / site design skills.

**Comment by jamessandy** [comment]
Hello @yochannah this is the logo redesign I did for BOSC I tried maintaining the color and the peat itself, hope you like ☺️☺️

![img-20181029-wa0012](https://user-images.githubusercontent.com/33603488/47639188-f6dfb700-db60-11e8-8c6b-c3333ca330db.jpg)

**Comment by peterjc** [comment]
@jamessandy I like the idea of an _open_ pear as a visual link to the open source / open science focus of BOSC. However, your logo looks like an Avocado pear (emoji 🥑), rather than traditional pear (emoji 🍐) from the Rosaceae plant family like apples - which is what we've used thus far. Little black seeds might be harder to draw and look good with a small logo though?

**Comment by jamessandy** [comment]
@peterjc am glad you like it. I think I would have to change the shape of the pear then 😉😉😉

**Comment by yochannah** [comment]
@jamessandy - The reason we use pear is because one type of pear is a "bosc pear" - https://en.wikipedia.org/wiki/Bosc_pear

An image for inspiration how pears could look internally might be something like: 
![image](https://user-images.githubusercontent.com/9271438/47679432-2bcd2780-dbbc-11e8-86d8-84aeef61e51e.png)

P.S. the design style you used above is very nice (I like the vector approach), so long as we could make it look a little more 🍐 and a little less 🥑 ;)

**Comment by myllah** [comment]
> So many nice contributions! @sakshi97 - the way the logo outline becomes the helix and merges in perfectly is nice! I think I like the leafy version better.
> 
> @simran-pandey wow, more logo contributions!
> 
> @myllah - The hand-drawn style and light bulb look is really unique! Can I ask what software you used to make it?
> 
> If I've missed anyone please let me know! <3 <3 <3

The software is called Autodesk SketchBook. I really recommend it. There are many colors, pens, pencils and brushes to choose.

**Comment by jamessandy** [comment]
Hello @yochannah  i tried reshaping and this is what i came up with.
![whatsapp image 2018-11-05 at 16 54 00](https://user-images.githubusercontent.com/33603488/48013326-f70d2300-e11b-11e8-9855-952ffce3fcbd.jpeg)

**Comment by JSENL** [comment]
I tried a more geometrical lined idea, it's a work-in-progress @yochannah 
![peardrawingi](https://user-images.githubusercontent.com/32881663/48034402-46a81a80-e12d-11e8-90e4-ccbe883f1689.png)

**Comment by yochannah** [comment]
Hey all - Looking over this issue there were _so many_ amazing designs. Since we've selected an intern and are moving on to the implementation phase I'll be closing this issue, but please remember - you are all awesome and we were privileged to have you work on our issues, even temporarily <3 ✨ 💖 🦄
