### ISSUE TITLE
Create alternate colours for the OBF logo

### ISSUE THREAD

**Issue by yochannah** [OBF/homepage-planning#2]
The OBF logo was recently refreshed and is a gorgeous minty green. We'd be interested in seeing other colours as well - perhaps including some rainbow / pride colour versions. Use your creativity!  

Current logo directory: https://github.com/OBF/obf-docs/tree/master/logos/new_logo

When you're ready, post your ideas in this thread for discussion and refinement. 

You'll be credited in the repo for your contribution as well as reaping eternal fame and glory. 

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), or if needed email yochannah@gmail.com

**Comment by simran-pandey** [comment]
Hey!
This looks interesting, Can I contribute to this too? :D

**Comment by simran-pandey** [comment]
![obf_logo_icon-circle-tr - copy](https://user-images.githubusercontent.com/31364051/46847020-e5c44580-cdff-11e8-9d65-b4eabebff8d6.jpg)
![obf_logo_icon-circle-tr](https://user-images.githubusercontent.com/31364051/46847030-f2e13480-cdff-11e8-9435-8824f9a59a0a.jpg)

I thought of giving your suggestion a go and I really liked how it gave the logo a dash of colors and a lot wider meaning. The open lock to me was depicting the open nature and adding the colors makes it look welcoming and inclusive. Do let me know what this version depicts to you :D

**Comment by kushinauwu** [comment]
Hi, I see there's already nice ideas on this logo design, is it okay if I contribute to this as well? Is it still open for more contributors? Thanks! :)

**Comment by yochannah** [comment]
@kushinauwu definitely! 👍

**Comment by yochannah** [comment]
@simran-pandey Of the two I think I like the coloured lock better - but I'm curious what it might look like with the rainbow replacing the green rather than filling in the gaps?

**Comment by simran-pandey** [comment]
@yochannah Ah I thought that the green color of the logo was to be retained! I should probably make a version along the lines of your feedback above, then we can see how it'll look in comparison to other versions :)

**Comment by simran-pandey** [comment]
![logo 4](https://user-images.githubusercontent.com/31364051/46889178-6e82c600-ce80-11e8-86d9-a39be9d33290.jpg)

![option3](https://user-images.githubusercontent.com/31364051/46889123-48f5bc80-ce80-11e8-8463-8f1e5cea2f75.jpg)

Hey! These are the two versions that I have created. Do let me know how you feel about these :)

**Comment by yochannah** [comment]
hmm, I think I like them both! Would be interested to hear if others have any feelings about this though... :)

**Comment by andrezasantana** [comment]
Hi,
I would like to contribute to this project.

**Comment by andrezasantana** [comment]
![2](https://user-images.githubusercontent.com/44169394/46963483-26c88e00-d07c-11e8-8676-dac9f322d892.png)
![1](https://user-images.githubusercontent.com/44169394/46963561-62fbee80-d07c-11e8-8073-9a23fd22ed31.png)


Hi! These are two versions I created.
what do you think?

**Comment by hasinifoss** [comment]
Hi @yochannah ,

I'd like to propose this logo. I used the alternative rainbow colors to represent helix like outer part of the logo.
![obf_logo_icon-circle-rainbow-colors](https://user-images.githubusercontent.com/2804179/46999534-84caa380-d158-11e8-85a7-f7e2179b726e.png)

If we need to preserve the green background we can keep this logo, otherwise I can change the background and will make another one.

**Comment by yochannah** [comment]
@hasinifoss don't worry, we don't need to keep the background!

**Comment by yochannah** [comment]
@ all: the ideas don't have to be rainbow! It might be nice to see some other solid colours too.

**Comment by yochannah** [comment]
@AndrezaSantana Wow, that's colourful! :) 

I think the lock needs to be a solid fill rather than stroked though.

**Comment by jamessandy** [comment]
Hello @yochannah so I tried playing around the logo and I did something new instead of the former but I'll also drop the present logo 
![img-20181026-wa0006](https://user-images.githubusercontent.com/33603488/47575174-58254180-d939-11e8-98b2-78e09b44ff8c.jpg)
when I changed the color

**Comment by jamessandy** [comment]
@yochannah you like it ?

**Comment by yochannah** [comment]
@jamessandy yes, it's pretty - thanks! I likethe colours and the sort of "bubbly" feel it has. 

We actually just _really_ recently [updated our logo](https://github.com/OBF/obf-docs/issues/43), but it's really lovely to see your creativity and design skills 👍

**Comment by jamessandy** [comment]
It's a pleasure @yochannah  will do well to drop the new color scheme I implemented on the  present logo

**Comment by yochannah** [comment]
we'd love to see that! :)

**Comment by jamessandy** [comment]
Ok @yochannah am back and this time I tried maintaining the original colors but made it aimpler and straight forward 
![img-20181029-wa0011](https://user-images.githubusercontent.com/33603488/47639534-cf3d1e80-db61-11e8-9cdf-e7b666016459.jpg)

**Comment by JSENL** [comment]
Hello, I tried my idea of the logo, it would be a layered multi-color with x and y dimensional shifts. I am still working on the opacity for the right color, but it should have a slight green overlay with a somewhat 'ghost' like background. @yochannah 
![logosignredo](https://user-images.githubusercontent.com/32881663/48017334-0aa89180-e0fc-11e8-9fa2-3d56b8f23c2c.jpg)

**Comment by yochannah** [comment]
Hey all - Looking over this issue there were _so many_ amazing designs. Since we've selected an intern and are moving on to the implementation phase I'll be closing this issue, but please remember - you are all awesome and we were privileged to have you work on our issues, even temporarily <3 ✨ 💖 🦄
